// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DoUpdate() {
  return window['go']['main']['App']['DoUpdate']();
}

export function GetISP() {
  return window['go']['main']['App']['GetISP']();
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function IsActive() {
  return window['go']['main']['App']['IsActive']();
}

export function StartBypass(arg1) {
  return window['go']['main']['App']['StartBypass'](arg1);
}

export function StopBypass() {
  return window['go']['main']['App']['StopBypass']();
}
