// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate():Promise<main.UpdateInfo>;

export function DoUpdate():Promise<void>;

export function GetISP():Promise<main.ISPInfo>;

export function GetServices():Promise<Array<main.ServiceInfo>>;

export function IsActive():Promise<boolean>;

export function StartBypass():Promise<void>;

export function StopBypass():Promise<void>;
